---
engines:
  tailor:
    enabled: true
ratings:
  paths:
  - "**.swift"
exclude_paths:
  - Coding_Challenge/Pods
  - Coding_Challenge/Coding_ChallengeTests
  - Coding_Challenge/Coding_ChallengeUITests

