source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Coding_Challenge' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'AlamofireObjectMapper', '~> 1.0'
    pod 'Alamofire', '~> 3.0'

end

target 'Coding_ChallengeTests' do

end

target 'Coding_ChallengeUITests' do

end
